apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pedido-app.fullname" . }}-config
  labels:
    {{- include "pedido-app.labels" . | nindent 4 }}
data:
  # URL de la base de datos con el nombre real del servicio
  {{- if .Values.db.enabled }}
  DATABASE_URL: "jdbc:postgresql://pedidos-app-db:5432/{{ .Values.db.auth.database }}"
  DATABASE_DRIVER: "org.postgresql.Driver"
  {{- else }}
  DATABASE_URL: "jdbc:postgresql://external-db:5432/pedidos_db"
  DATABASE_DRIVER: "org.h2.Driver"
  {{- end }}

  # Configuraciones de la aplicación
  APP_NAME: "Sistema de Gestión de Pedidos"
  APP_VERSION: {{ .Chart.AppVersion | quote }}

  # Zona horaria
  TZ: "America/Bogota"

  # Puerto del servidor
  SERVER_PORT: {{ .Values.service.port | quote }}